# Generated by Django 5.2.1 on 2025-05-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
